symfony/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use PhpParser\Node\Scalar\String_;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="email_UNIQUE", columns={"email"}), @ORM\UniqueConstraint(name="iduser_UNIQUE", columns={"idUser"})})
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Email already taken"
 *     )
 */
class User implements UserInterface
{

    // Defines the different role of the application
    public $ROLES = array('ROLE_STUDENT', 'ROLE_TEACHER', 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN');

    /**
     * @var int
     *
     * @ORM\Column(name="idUser", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $iduser;

    /**
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=15, nullable=false)
     */
    private $first_name;

    /**
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=15, nullable=false)
     */
    private $last_name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=45, nullable=false)
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=1000, nullable=false)
     * @Assert\Length(min="8", minMessage="Too short : 8 character minimum")
     */
    private $password;

    /**
     * @var string
     *
     * @Assert\EqualTo(propertyPath="password", message="Passwords not corresponding")
     */
    public $confirm_password;

    /**
     * @var bool
     *
     * @ORM\Column(name="banned", type="boolean", nullable=false)
     */
    private $banned;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="ban_date", type="datetime")
     */
    private $ban_date;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="ban_end_date", type="datetime")
     */
    private $ban_end_date;

    /**
     * @var string
     *
     * @ORM\Column(name="securityCode", type="string")
     */
    private $security_code;

    /**
     * @var bool
     *
     * @ORM\Column(name="activated", type="boolean")
     */
    private $activated;

    /**
     * @var float|null
     *
     * @ORM\Column(name="evaluation", type="float", nullable=true, options={"default"="NULL"})
     */
    private $evaluation = null;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /// GETTERS AND SETTERS     ///

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Onlineorder", mappedBy="iduser")
     */
    private $Onlineorders;


    public function __construct()
    {
        $this->Onlineorders=new ArrayCollection();
        $this->idproviders=new ArrayCollection();
    }

    public function getIduser(): ?int
    {
        return $this->iduser;
    }

    public function getFirstname(): ?string
    {
        return $this->first_name;
    }

    public function setFirstname(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->last_name;
    }

    public function setLastname(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBanned(): ?bool
    {
        return $this->banned;
    }

    public function setBanned(bool $banned): self
    {
        $this->banned = $banned;

        return $this;
    }

    public function getBan_Date(): ?\DateTime
    {
        return $this->ban_date;
    }

    public function getBan_Date_String(): ?string
    {
        return $this->ban_date->format("Y-m-d H:i:s");
    }

    public function setBan_date( $ban_date): self
    {
        $this->ban_date = $ban_date;

        return $this;
    }

    public function getBan_end_date(): ?\DateTime
    {
        return $this->ban_end_date;
    }

    public function getBan_End_Date_String(): ?string
    {
        return $this->ban_end_date->format("Y-m-d H:i:s");
    }

    public function setBan_End_Date($ban_end_date): self
    {
        $this->ban_end_date = $ban_end_date;

        return $this;
    }

    public function getSecurityCode(): ?string
    {
        return $this->security_code;
    }

    public function setSecurityCode($securityCode): self
    {
        $this->security_code = $securityCode;

        return $this;
    }

    public function getActivated(): ?bool
    {
        return $this->activated;
    }

    public function setActivated($activated): self
    {
        $this->activated = $activated;

        return $this;
    }

    public function getEvaluation(){
        return $this->evaluation;
    }

    public function setEvaluation($new){
        $this->evaluation=$new;
    }

    ///     UserInterface functions

    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getOnlineOrders()
    {
        return $this->Onlineorders;
    }

    public function addOnlineOrder(Onlineorder $onlineorder){
        if (!$this->Onlineorders->contains($onlineorder)) {
            $this->Onlineorders[] = $onlineorder;
            $onlineorder->setIduser($this);
        }
        return $this;
    }

    public function removeOnlineOrder(Onlineorder $onlineorder){
        if ($this->Onlineorders->contains($onlineorder)) {
            $this->Onlineorders->removeElement($onlineorder);
            // set the owning side to null (unless already changed)
            if ($onlineorder->getIduser() === $this) {
                $onlineorder->setIduser(null);
            }
        }
        return $this;
    }

}

symfony/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('password', PasswordType::class)
            ->add('confirm_password', PasswordType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

symfony/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Evaluation;
use App\Entity\User;
use App\Form\PasswordType;
use App\Form\UserEditType;
use App\Form\UserType;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\EncoderFactory;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @Route("/user")
 */
class UserController extends SecurityController
{

    ////////////////
    ///  ROUTES  ///
    ////////////////

    /**
     * Requires ADMIN_ROLE
     *
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $ban = true;
        $role = '["ROLE_STUDENT"]';

        $value = $request->query->get('users');

        switch ($value){
            case 2 :
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByRole($role);
                break;
            case 3 :
                $role = '["ROLE_TEACHER"]';
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByRole($role);
                break;
            case 4 :
                $role = '["ROLE_ADMIN"]';
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByRole($role);
                break;
            case 5 :
                $role = '["ROLE_SUPER_ADMIN"]';
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByRole($role);
                break;
            case 6 :
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByBan($ban);
                break;
            case 7 :
                $ban = false;
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findByBan($ban);
                break;
            default:
                $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findAll();
                break;
        }

        return $this->render('user/index.html.twig', [
            'title' => 'User Index',
            'headtitle' => 'View all the users list',
            'users' => $users,
        ]);
    }


    /**
     * @Route("/{iduser}", name="user_show", methods={"GET", "POST"})
     */
    public function show(User $user_rated, Request $request)
    {
        $user_rater=$this->getUser();
        $this->denyAccssIfNotActivated($user_rater);
        $count=0;
        $value=null;
        $lastEvaluation=null;
        //Check if the list of article has been cleared for this session
        $list=$this->container->get('session')->get('list');
        if($list){
            $list->clear();
        }
        // Accessible by the user and the ADMIN and higher
        if( !$this->isGranted('ROLE_ADMIN') && !$this->isSelfUser($user_rater)){
            throw new AccessDeniedException();
        }

        if($request->request->has("rate")){
            while($count<6 && !$value){
                $value=$request->request->get("rate");
                $this->evaluateUser($user_rated, $user_rater, $value);
            }
        }

        $formerEval=$this->getDoctrine()->getRepository(Evaluation::class)->findOneBy(["idrater"=>$user_rater->getIduser(), "idrated"=>$user_rated->getIduser()]);

        if($formerEval){
            $lastEvaluation=$formerEval->getRate();
        }

        return $this->render('user/show.html.twig', [
            'title' => "My Account",
            'user' => $user_rated,
            'last_evaluation'=>$lastEvaluation,
            'nbVotes'=>$this->getEvaluationsAmount($user_rated)
        ]);
    }

    /**
     * @Route("/{iduser}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user)
    {
        $this->denyAccssIfNotActivated($user);
        // Accessible by the user and SUPER ADMIN
        if( !$this->isGranted('ROLE_SUPER_ADMIN') && !$this->isSelfUser($user)){
            throw new AccessDeniedException();
        }

        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $em=$this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('user_show', [
                'iduser' => $user->getIduser(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'title' => 'Edit',
            'headtitle' => 'Edit your information',
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{iduser}/edit/Password", name="user_edit_password", methods={"GET","POST"})
     */
    public function editPassword(Request $request, User $user, UserPasswordEncoderInterface $encoder)
    {
        $this->denyAccssIfNotActivated($user);
        $this->denyAccessIfNotCurrentUser($user);

        $session=$this->container->get('session');
        if(!$session->get('formerUser')){
            $session->set('formerUser', $user);
        }
        $formerUser=$session->get('formerUser');
        $form = $this->createForm(PasswordType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $psw1=$form->get("password")->getData();
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);

            if($encoder->isPasswordValid($formerUser,$form->get('currentPassword')->getData())){

                $user->setPassword($encoder->encodePassword($user, $psw1));
                $session->remove('formerUser');

            }else{
                $error="Unvalid password";
                $user->setPassword( $formerUser->getPassword());
                $this->save($user);
                return $this->render('user/edit_Password.html.twig', [
                    'title' => 'Edit password',
                    'headtitle' => 'Change your password',
                    'form' => $form->createView(),
                    'user' => $user,
                    'error' => $error ,
                ]);
            }

            $this->save($user);
            return $this->redirectToRoute('user_index');

        }
        return $this->render('user/edit_Password.html.twig', [
            'title' => 'Edit password',
            'headtitle' => 'Change your password',
            'form' => $form->createView(),
            'user' => $user
        ]);
    }

    /**
     * @Route("/{iduser}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user)
    {
        $this->denyAccssIfNotActivated($user);
        // Accessible by the user and SUPER ADMIN
        if( !$this->isGranted('ROLE_SUPER_ADMIN') && !$this->isSelfUser($user)){
            throw new AccessDeniedException();
        }

        $submittedToken = $request->request->get('_token');

        if ($this->isCsrfTokenValid('delete'.$user->getIduser(), $submittedToken)) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }
        return $this->redirectToRoute('user_index');
    }

    /**
     * @Route("/{iduser}/ban", name="user_ban")
     */
    public function ban(\Swift_Mailer $mailer, Request $request, User $user){

        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $submittedToken = $request->request->get('_token');

        $isBanned = $user->getBanned();

        if ( !$isBanned && $this->isCsrfTokenValid('ban'.$user->getIduser(), $submittedToken)) {
            $now = new \DateTime('NOW');

            // Ban for 500 years if super admin or 12 days if admin
            if($this->isGranted('ROLE_SUPER_ADMIN')){
                $expiration = new \DateTime('NOW +500 years');
            }
            elseif ($this->isGranted('ROLE_ADMIN')){
                $expiration = new \DateTime('NOW +14 days');
            }

            $user->setBanned(true);
            $user->setBan_date($now);
            $user->setBan_end_date($expiration);

            $this->save($user);

            // Sends an email when a user is banned
            $this->sendEmail($mailer, 'Banned', $user, 'emails/banned.html.twig', [
                'user' => $user ]);

            return $this->redirectToRoute('user_show', [
                'iduser' => $user->getIduser(),
            ]);

        }
        elseif ( $isBanned && $this->isCsrfTokenValid('ban'.$user->getIduser(), $submittedToken)) {
            $user->setBanned(false);
            $user->setBan_date(null);
            $user->setBan_end_date( null);
            $this->save($user);
        }

        return $this->redirectToRoute('user_show', [
            'iduser' => $user->getIduser(),
        ]);
    }

    /**
     * @Route("/{iduser}/set_admin", name="user_set_admin")
     */
    public function setAdmin(Request $request, User $user){

        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $submittedToken = $request->request->get('_token');
        $roles = $user->getRoles();

        if ( $roles[0] != 'ROLE_ADMIN' && $this->isCsrfTokenValid('set_admin'.$user->getIduser(), $submittedToken)) {
            $user->setRoles(array($user->ROLES[2]));
            $this->save($user);

symfony/templates/user/_admin_form.html.twig
{# This file manages the interface of set admin button #}

{% if user.roles[0] != 'ROLE_STUDENT' %}

    {% if is_granted('ROLE_SUPER_ADMIN') and not isSelfUser and user.roles[0] != 'ROLE_ADMIN' %}

        <form method="post" action="{{ path('user_set_admin', {'iduser': user.iduser}) }}" onsubmit="return confirm('Are you sure you set this user ROLE ADMIN?');">
            <input type="hidden" name="_token" value="{{ csrf_token('set_admin' ~ user.iduser) }}">
            <button class="btn btn-success" type="submit">Set Admin</button>
        </form>

    {% elseif is_granted('ROLE_SUPER_ADMIN') and not isSelfUser and user.roles[0] == 'ROLE_ADMIN' %}

        <form method="post" action="{{ path('user_set_admin', {'iduser': user.iduser}) }}" onsubmit="return confirm('Are you sure you remove this user ROLE ADMIN?');">
            <input type="hidden" name="_token" value="{{ csrf_token('unset_admin' ~ user.iduser) }}">
            <button class="btn btn-danger" type="submit">Unset Admin</button>
        </form>

    {% endif %}
{% endif %}

symfony/templates/user/_ban_form.html.twig
{# This templates manages the ban and unban of users #}

{% set isUserAtLeastAdmin = user.roles[0] == 'ROLE_ADMIN' or user.roles[0] == 'ROLE_SUPER_ADMIN'%}

{% if not isUserAtLeastAdmin or is_granted('ROLE_SUPER_ADMIN')%}

    {% if user.banned == false %}

        <form method="post" action="{{ path('user_ban', {'iduser': user.iduser}) }}" onsubmit="return confirm('Are you sure you want to ban this user?');">
            <input type="hidden" name="_token" value="{{ csrf_token('ban' ~ user.iduser) }}">
            <button class="btn btn-danger" type="submit">Ban user</button>
        </form>

    {% else %}

        <form method="post" action="{{ path('user_ban', {'iduser': user.iduser}) }}" onsubmit="return confirm('Are you sure you want to unban this user?');">
            <input type="hidden" name="_token" value="{{ csrf_token('ban' ~ user.iduser) }}">
            <button class="btn btn-success" type="submit">Unban user</button>
        </form>

    {% endif %}

{% endif %}

symfony/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'iduser': user.iduser}) }}" onsubmit="return confirm('Are you sure you want to delete this account?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.iduser) }}">
    <button class="btn btn-danger disabled">Delete this account</button>
</form>

symfony/templates/user/_form.html.twig
{# Thème de formulaire bootstrap #}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

symfony/templates/user/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}


{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-3">{{ headtitle }}</h1>
        <hr class="my-4">

        <h3> <strong>Email :</strong> {{ user.email }}</h3>

        {{ form_start(form) }}

        {{ form_row(form.first_name) }}
        {{ form_row(form.last_name) }}

        <button type="button" class="btn btn-link" onclick="window.location.href = '{{ path("user_edit_password", {'iduser': app.user.iduser}) }}';">Change current password</button>
        <br><br>

        <button class="btn btn-success">{{ button_label|default('Save') }}</button><br><br>

        <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path("user_show", {'iduser': app.user.iduser}) }}';">Back to your account</button>


    </div>

{% endblock %}

symfony/templates/user/edit_Password.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}


{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-3">{{ headtitle }}</h1>
        <hr class="my-4">

        <h3> <strong>Email :</strong> {{ user.email }}</h3>

        <br>
        {{ form_start(form) }}
        <p><b>Enter your current password</b></p><br>
        {%  if error is defined %}
            <p  style="color:red;">{{ error }}</p>
        {% endif %}
        {{ form_row(form.currentPassword, { 'attr': {'placeholder': "Current password" }}) }}
        <br>
        <p><b>Enter your new password</b></p><br>
        {{ form_row(form.password, { 'attr': {'placeholder': "New password" }}) }}
        {{ form_row(form.confirm_password, { 'attr': {'placeholder': "Confirm password" }}) }}

        <button class="btn btn-success">{{ button_label|default('Save') }}</button><br><br>

        <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path("user_show", {'iduser': app.user.iduser}) }}';">Back to your account</button>

    </div>

{% endblock %}

symfony/templates/user/index.html.twig
{% extends 'base.html.twig' %}



{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1 class="display-3">{{ headtitle }}</h1>
        <p class="lead">Here you will find a list of all the users of the system</p>

        <hr class="my-4">

        <form class="form-group" action="{{ path('user_index') }}" method="get">
            <table class="table">
                <tr>
                    <td>
                        <select class="custom-select" name="users">
                            <option selected="">Which users to you want to see ?</option>
                            <option value="1">All</option>
                            <option value="2">Students</option>
                            <option value="3">Teachers</option>
                            <option value="4">Admins</option>
                            <option value="5">Super Admin</option>
                            <option value="6">Banned</option>
                            <option value="7">Unbanned</option>
                        </select>
                    </td>
                    <td>
                        <button class="btn-secondary" type="submit" value="Submit">Submit</button>
                    </td>
                </tr>
            </table>

        </form>

        <hr class="my-4">

        <p class="lead">

        <table class="table">
            <thead>
            <tr>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Banned</th>
                <th>Role</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.firstname }}</td>
                    <td>{{ user.lastname }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.banned ? '<p style="color:red;">Yes</p>' : '<p style="color:green;">No</p>' }}</td>
                    <td>
                        {% for role in user.roles %}
                        {{ role }}
                        {% endfor %}
                    </td>
                    <td>
                        <button type="button" class="btn btn-success btn-sm" onclick="window.location.href = '{{ path('user_show',  {'iduser': user.iduser }) }}';">Show</button>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        </p>
    </div>

{% endblock %}

symfony/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% set isSelfUser = app.user and app.user.iduser == user.iduser %}

{% block title %}My Account{% endblock %}

{% block body %}

    <div class="jumbotron">

        <h1 class="display-3">{{ user.firstName }} {{ user.lastName }}</h1>

        <p class="lead">
            {% if isSelfUser %}
                Hello {{ user.firstName }}, this is your account,
                you can find your information and the orders you've made.
            {% else %}
                Welcome on {{ user.firstName }} {{ user.lastName }} profile.
            {% endif %}

        </p>

        <hr class="my-4">

        <p class="lead"></p>

        <table class="table">

            <tbody>
            <tr>
                <th>First name</th>
                <td>{{ user.firstname }}</td>

                <th></th>
                <td>
                    {% for role in user.roles %}
                        <span class="badge badge-pill badge-success">{{ role }}</span>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Last name</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>Email adress</th>
                <td>{{ user.email }}</td>
            </tr>

            {% if isSelfUser %}
                <tr>
                    <th>Password</th>
                    <td>•••••••••••••••</td>
                </tr>
            {% endif %}

            {% if is_granted('ROLE_ADMIN') and not isSelfUser %}
                <tr>
                    <th>Evaluation</th>
                    {% if user.evaluation != null %}
                        <td>{{ user.evaluation }}/5  ({{ nbVotes }} votes)</td>
                    {% else %}
                        <td>Not evaluated yet...</td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Evalutate</th>
                    <td>
                        {% if last_evaluation != null %}
                            Your last evalution : {{ last_evaluation }}/5 <br>
                        {% endif %}

                        <div class="rate">
                            <form class="rate" action="{{ path('user_show', {'iduser': user.iduser }) }}" method="post">
                                <input type="radio" id="star5" name="rate" value="5" />
                                <label for="star5" title="text">5 stars</label>
                                <input type="radio" id="star4" name="rate" value="4" />
                                <label for="star4" title="text">4 stars</label>
                                <input type="radio" id="star3" name="rate" value="3" />
                                <label for="star3" title="text">3 stars</label>
                                <input type="radio" id="star2" name="rate" value="2" />
                                <label for="star2" title="text">2 stars</label>
                                <input type="radio" id="star1" name="rate" value="1" />
                                <label for="star1" title="text">1 star</label>
                                <td></td>
                                <td><button type="submit" value="submit" class="btn btn-warning">Rate it</button></td>
                            </form>
                        </div>
                    </td>
                </tr>

                <tr>
                    <th>Banned</th>
                    <td>{{ user.banned ? '<p style="color:red;">Yes</p>' : '<p style="color:green;">No</p>' }}</td>

                    <th></th>
                    <td>
                        {{ include('user/_ban_form.html.twig') }}
                    </td>
                </tr>

                {% if user.ban_date != null and user.ban_end_date != null %}
                    <tr>
                        <th>Ban date</th>
                        <td>{{ user.Ban_Date_String }}</td>
                    </tr>
                    <tr>
                        <th>Ban end date</th>
                        <td>{{ user.Ban_End_Date_String }}</td>
                    </tr>
                {% endif %}

            {% endif %}
            </tbody>
        </table>

        <br><br>

        {% if isSelfUser %}
            <table>
                <tbody>
                <tr>
                    <td>
                        <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path('articleList', {'iduser': user.iduser}) }}';">Order new items</button>
                        <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path('onlineorder_showAll', {'iduser': user.iduser}) }}';">See my orders</button>

                    </td>
                </tr>
        {% endif %}
            </tbody>
        </table>

        <br><br>

                <tr>
                    <td>
                        {{ include('user/_admin_form.html.twig') }}

                        <button onclick="window.location.href = '{{ path('user_edit',{'iduser' : user.iduser}) }}';"
                                type="button" class="btn btn-outline-info">Edit this account</button>

                    </td>
                </tr>
                </tbody>
            </table>

    </div>
{% endblock %}